const SEED_DATA = {
  "lancamentos": [
    {
      "id": "seed-2",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Seg",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 136.0,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-3",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Ter",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 121.46,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-4",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Qua",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 143.8,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-5",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Qui",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 24.16,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-6",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Sex",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-7",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Sab",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-8",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Dom",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 325.44,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-9",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Total semanal de combustivel",
      "valor": 100.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-10",
      "data": null,
      "mes": "Março",
      "semana": "Semana 1",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Total semanal de manutencao",
      "valor": 87.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-11",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Seg",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 47.75,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-12",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Ter",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 136.24,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-13",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Qua",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 88.19,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-14",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Qui",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 125.32,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-15",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Sex",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-16",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Sab",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 211.19,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-17",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Dom",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 48.35,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-18",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Total semanal de combustivel",
      "valor": 120.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-19",
      "data": null,
      "mes": "Março",
      "semana": "Semana 2",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Total semanal de manutencao",
      "valor": 160.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-20",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Seg",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 162.08,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-21",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Ter",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 27.65,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-22",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Qua",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-23",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Qui",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 167.0,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-24",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Sex",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-25",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Sab",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 204.53,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-26",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Dom",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-27",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Total semanal de combustivel",
      "valor": 60.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-28",
      "data": null,
      "mes": "Março",
      "semana": "Semana 3",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Total semanal de manutencao",
      "valor": 37.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-29",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Seg",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 103.8,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-30",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Ter",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 102.13,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-31",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Qua",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 98.03,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-32",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Qui",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 152.68,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-33",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Sex",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-34",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Sab",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 309.92,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-35",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Dom",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 191.81,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-36",
      "data": null,
      "mes": "Março",
      "semana": "Semana 4",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Total semanal de combustivel",
      "valor": 120.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-37",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Seg",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-38",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Ter",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 192.73,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-39",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Qua",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 151.47,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-40",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Qui",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 160.63,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-41",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Sex",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-42",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Sab",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 164.78,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-43",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Dom",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 149.71,
      "km": null,
      "observacao": "Migrado da planilha antiga; apps estavam somados",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-44",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Total semanal de combustivel",
      "valor": 100.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-45",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 1",
      "diaSemana": "Fechamento da semana",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Total semanal de manutencao",
      "valor": 107.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-46",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Seg",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": "Migrado da planilha antiga",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-47",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Ter",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 89.23,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-48",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Ter",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-49",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Ter",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 68.08,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-50",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Qua",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 119.66,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-51",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Qua",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 18.08,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-52",
      "data": null,
      "mes": "Abril",
      "semana": "Semana 2",
      "diaSemana": "Qua",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-53",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Qua",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 63.26,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-54",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Qua",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-55",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Qua",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 136.76,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-56",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Qui",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 150.58,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-57",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Qui",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-58",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Sex",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 35.39,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-59",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Sab",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 288.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-60",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Sab",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 48.61,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-61",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Sab",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-62",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Dom",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 10.61,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-63",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Dom",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 235.75,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-64",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 1",
      "diaSemana": "Dom",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Faturamento do dia",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-65",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Seg",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Troca de Óleo",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-66",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Seg",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-67",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Ter",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 188.02,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-68",
      "data": null,
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Ter",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-69",
      "data": "2026-07-08T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 16.13,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-70",
      "data": "2026-07-08T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 93.61,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-71",
      "data": "2026-07-08T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-72",
      "data": "2026-07-09T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Quinta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 146.79,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-73",
      "data": "2026-07-09T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Quinta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 31.88,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-74",
      "data": "2026-07-09T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-75",
      "data": "2026-07-10T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-76",
      "data": "2026-07-11T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 280.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-77",
      "data": "2026-07-11T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-78",
      "data": "2026-07-12T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Domingo",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 75.72,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-79",
      "data": "2026-07-12T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Domingo",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 236.46,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-80",
      "data": "2026-07-12T00:00:00",
      "mes": "Julho",
      "semana": "Semana 2",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-81",
      "data": "2026-07-13T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 120.18,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-82",
      "data": "2026-07-13T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Segunda",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 23.35,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-83",
      "data": "2026-07-13T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 15.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-84",
      "data": "2026-07-14T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-85",
      "data": "2026-07-15T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3 ",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 67.62,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-86",
      "data": "2026-07-15T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 32.21,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-87",
      "data": "2026-07-15T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 10.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-88",
      "data": "2026-07-16T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 11.25,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-89",
      "data": "2026-07-16T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 115.17,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-90",
      "data": "2026-07-16T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 25.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-91",
      "data": "2026-07-16T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Troca de Óleo",
      "valor": 35.0,
      "km": null,
      "observacao": null,
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-92",
      "data": "2026-07-16T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Extensor",
      "valor": 10.0,
      "km": null,
      "observacao": null,
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-93",
      "data": "2026-07-17T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Sexta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 14.07,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-94",
      "data": "2026-07-17T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 8.02,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-95",
      "data": "2026-07-18T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 169.93,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-96",
      "data": "2026-07-18T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 31.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-97",
      "data": "2026-07-18T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-98",
      "data": "2026-07-19T00:00:00",
      "mes": "Julho",
      "semana": "Semana 3",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-99",
      "data": "2026-07-20T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 96.49,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-100",
      "data": "2026-07-20T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 15.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-101",
      "data": "2026-07-21T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-102",
      "data": "2026-07-22T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 134.82,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-103",
      "data": "2026-07-23T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Quinta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 57.26,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-104",
      "data": "2026-07-22T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 17.23,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-105",
      "data": "2026-07-22T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-106",
      "data": "2026-07-22T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Relação ",
      "valor": 140.0,
      "km": null,
      "observacao": null,
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-107",
      "data": "2026-07-22T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Capa do Banco",
      "valor": 70.0,
      "km": null,
      "observacao": null,
      "referencia": "Semanal",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-108",
      "data": "2026-07-24T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 117.14,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-109",
      "data": "2026-07-24T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-110",
      "data": "2026-07-25T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 114.9,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-111",
      "data": "2026-07-25T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 8.11,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-112",
      "data": "2026-07-25T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-113",
      "data": "2026-07-26T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Domingo",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 76.46,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-114",
      "data": "2026-07-26T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Domingo",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 163.85,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-115",
      "data": "2026-07-26T00:00:00",
      "mes": "Julho",
      "semana": "Semana 4",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-116",
      "data": "2026-07-27T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-117",
      "data": "2026-07-28T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Terça",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 66.47,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-118",
      "data": "2026-07-28T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 41.17,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-119",
      "data": "2026-07-29T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Quarta",
      "app": "iFood/99Food (junto)",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 146.24,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-120",
      "data": "2026-07-29T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-121",
      "data": "2026-07-30T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-122",
      "data": "2026-07-31T00:00:00",
      "mes": "Julho",
      "semana": "Semana 5",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-123",
      "data": "2026-08-01T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 322.51,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-124",
      "data": "2026-08-01T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-125",
      "data": "2026-08-02T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Domingo",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 10.5,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-126",
      "data": "2026-08-03T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 81.09,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-127",
      "data": "2026-08-03T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 20.84,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-128",
      "data": "2026-08-03T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-129",
      "data": "2026-08-04T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 10.55,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-130",
      "data": "2026-08-04T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 15.41,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-131",
      "data": "2026-08-05T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 79.26,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-132",
      "data": "2026-08-05T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 57.48,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-133",
      "data": "2026-08-05T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-134",
      "data": "2026-08-06T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-135",
      "data": "2026-08-07T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 136.28,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-136",
      "data": "2026-08-07T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 1",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-137",
      "data": "2026-08-08T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 22.22,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-138",
      "data": "2026-08-08T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 170.37,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-139",
      "data": "2026-08-08T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-140",
      "data": "2026-08-09T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Domingo",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 15.88,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-141",
      "data": "2026-08-10T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Segunda",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 50.52,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-142",
      "data": "2026-08-10T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 77.92,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-143",
      "data": "2026-08-10T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-144",
      "data": "2026-08-10T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Troca de Óleo",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-145",
      "data": "2026-08-11T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 152.68,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-146",
      "data": "2026-08-11T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 10.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-147",
      "data": "2026-08-11T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 18.03,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-148",
      "data": "2026-08-12T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 123.84,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-149",
      "data": "2026-08-12T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 33.46,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-150",
      "data": "2026-08-12T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-151",
      "data": "2026-08-13T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-152",
      "data": "2026-08-14T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 15.28,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-153",
      "data": "2026-08-14T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 127.56,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-154",
      "data": "2026-08-14T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-155",
      "data": "2026-08-15T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 184.35,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-156",
      "data": "2026-08-15T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 51.73,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-157",
      "data": "2026-08-15T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-158",
      "data": "2026-08-16T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-159",
      "data": "2026-08-17T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-160",
      "data": "2026-08-18T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 44.68,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-161",
      "data": "2026-08-18T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 42.57,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-162",
      "data": "2026-08-18T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-163",
      "data": "2026-08-19T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-164",
      "data": "2026-08-20T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-165",
      "data": "2026-08-21T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 3",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-166",
      "data": "2026-08-22T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 66.16,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-167",
      "data": "2026-08-23T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-168",
      "data": "2026-08-24T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 71.22,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-169",
      "data": "2026-08-24T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Segunda",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 43.16,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-170",
      "data": "2026-08-24T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-171",
      "data": "2026-08-25T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-172",
      "data": "2026-08-26T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 120.54,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-173",
      "data": "2026-08-26T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-174",
      "data": "2026-08-27T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-175",
      "data": "2026-08-28T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 171.79,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-176",
      "data": "2026-08-28T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 4",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-177",
      "data": "2026-08-29T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 36.34,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-178",
      "data": "2026-08-29T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 314.73,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-179",
      "data": "2026-08-29T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Faturamento do dia",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-180",
      "data": "2026-08-29T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 17.43,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-181",
      "data": "2026-08-30T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-182",
      "data": "2026-08-31T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Segunda",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 12.63,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-183",
      "data": "2026-08-31T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 118.07,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-184",
      "data": "2026-08-31T00:00:00",
      "mes": "Agosto",
      "semana": "Semana 5",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-185",
      "data": "2026-08-01T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 10.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-186",
      "data": "2026-08-01T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-187",
      "data": "2026-08-02T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 92.17,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-188",
      "data": "2026-08-02T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 14.04,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-189",
      "data": "2026-08-02T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 16.67,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-190",
      "data": "2026-08-02T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 10.55,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-191",
      "data": "2026-08-02T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-192",
      "data": "2026-08-03T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-193",
      "data": "2026-08-04T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-194",
      "data": "2026-08-05T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 355.17,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-195",
      "data": "2026-08-05T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 56.78,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-196",
      "data": "2026-08-05T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 13.1,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-197",
      "data": "2026-08-05T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-198",
      "data": "2026-08-06T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-199",
      "data": "2026-08-07T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 244.46,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-200",
      "data": "2026-08-07T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Pneu Furado",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-201",
      "data": "2026-08-07T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-202",
      "data": "2026-08-07T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 1",
      "diaSemana": "Segunda",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 7.79,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-203",
      "data": "2026-08-08T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 100.55,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-204",
      "data": "2026-08-08T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 20.58,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-205",
      "data": "2026-08-08T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-206",
      "data": "2026-08-08T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 27.15,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-207",
      "data": "2026-08-08T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 9.82,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-208",
      "data": "2026-08-08T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Manutencao",
      "descricao": "Troca de Óleo",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-209",
      "data": "2026-08-09T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 8.05,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-210",
      "data": "2026-08-09T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-211",
      "data": "2026-08-09T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 102.89,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-212",
      "data": "2026-08-09T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Quarta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 21.88,
      "km": null,
      "observacao": "Após meia noite",
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-213",
      "data": "2026-09-10T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-214",
      "data": "2026-09-11T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 182.72,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-215",
      "data": "2026-09-11T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-216",
      "data": "2026-09-11T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Sexta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 17.07,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-217",
      "data": "2026-09-12T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 247.14,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-218",
      "data": "2026-09-12T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 30.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-219",
      "data": "2026-09-13T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-220",
      "data": "2026-09-14T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 83.45,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-221",
      "data": "2026-09-14T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 2",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-222",
      "data": "2026-09-15T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 109.15,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-223",
      "data": "2026-09-15T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 16.75,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-224",
      "data": "2026-09-15T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Terça",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-225",
      "data": "2026-09-16T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Quarta",
      "app": null,
      "tipo": "Controle",
      "categoria": "Folga",
      "descricao": "Dia de folga",
      "valor": 0.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-226",
      "data": "2026-09-17T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 56.18,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-227",
      "data": "2026-09-17T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 127.91,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-228",
      "data": "2026-09-17T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Quinta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-229",
      "data": "2026-09-18T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Sexta",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 97.96,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-230",
      "data": "2026-09-18T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Sexta",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 15.86,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-231",
      "data": "2026-09-18T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Sexta",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-232",
      "data": "2026-09-19T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 338.15,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-233",
      "data": "2026-09-19T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 23.16,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-234",
      "data": "2026-09-19T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Sabado",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 40.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-235",
      "data": "2026-09-20T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Domingo",
      "app": "iFood",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 2.4,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-236",
      "data": "2026-09-20T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Domingo",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 159.32,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-237",
      "data": "2026-09-20T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Domingo",
      "app": null,
      "tipo": "Despesa",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    },
    {
      "id": "seed-238",
      "data": "2026-09-21T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Segunda",
      "app": "99Food",
      "tipo": "Receita",
      "categoria": "Entrega",
      "descricao": "Faturamento do dia",
      "valor": 133.63,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 10.0
    },
    {
      "id": "seed-239",
      "data": "2026-09-21T00:00:00",
      "mes": "Setembro",
      "semana": "Semana 3",
      "diaSemana": "Segunda",
      "app": null,
      "tipo": "Controle",
      "categoria": "Combustivel",
      "descricao": "Combustivel",
      "valor": 20.0,
      "km": null,
      "observacao": null,
      "referencia": "Diario",
      "valorGuardado": 0.0
    }
  ]
};
